# Generated by Django 5.1.4 on 2025-02-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_cpf_alter_cliente_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
